os: osx
osx_image: xcode10.1

before_install:
  - rvm --default use 2.4.5

install:
  - gem install cocoapods
  - pod install

script:
  - xcodebuild -sdk iphonesimulator -workspace ToDoList.xcworkspace -scheme ToDoList -configuration Release clean build -derivedDataPath builddata/